name: Build and Deploy To-Do App

# Déclenchement du workflow sur push ou pull request sur la branche "main"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser Ubuntu pour exécuter les étapes

    steps:
    # Étape 1 : Cloner le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Installer Docker (si nécessaire) et configurer Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Étape 3 : Construire l'image Docker pour l'application
    - name: Build Docker image
      run: |
        docker build -t todo-app .

    # Étape 4 : Se connecter à DockerHub
    - name: Log in to DockerHub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # Étape 5 : Pousser l'image Docker vers DockerHub
    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/todo-app
